apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
spec:
  selector:
    matchLabels:
      app: inventory-management
  replicas: 2
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
        - name: inventory-management
          image: inventorymanagement-node
          ports:
            - containerPort: 3000
